INSERT INTO menu_categories (name, description, sort_order)
VALUES
  ('Snacks', NULL, 1),
  ('Charcoal Grill', NULL, 2),
  ('Mains', NULL, 3),
  ('Accompaniments', NULL, 4),
  ('Shared Dish', NULL, 5),
  ('Desserts', NULL, 6),
  ('Kids Menu', NULL, 7),
  ('Drinks', NULL, 8),
  ('Coffee', NULL, 9),
  ('Featured', NULL, 10);

INSERT INTO menu_items (category_id, name, description, price_cents)
VALUES
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Loitta Fish Fry', NULL, 52500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Spicy Chingri Skewers', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Battered Calamari', NULL, 59500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Tandoori Prawn Skewers', NULL, 62500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Boneless Chicken Chaap', NULL, 49500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Chicken Tikka Porota Roll', NULL, 39500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Minced Beef Porota Roll', NULL, 49500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Fusion Phuchka', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Maki Roll', NULL, 38500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Cream of Mushroom Soup', NULL, 32500),
  ((SELECT id FROM menu_categories WHERE name = 'Snacks'), 'Club Sandwich', NULL, 44500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Chicken Tikka', NULL, 49500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Reshmi Kabab', NULL, 54500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Chicken Tandoori (Half)', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Chicken Tengri Kabab', NULL, 58500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Beef Seekh Kabab', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Mutton Seekh Kabab', NULL, 69500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Beef Boti Kabab', NULL, 69500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Mutton Boti Kabab', NULL, 69500),
  ((SELECT id FROM menu_categories WHERE name = 'Charcoal Grill'), 'Rushtom', NULL, 69500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Prawn Malai Curry', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Seafood Malai Curry', NULL, 109500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Shorshe Ilish', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Deep Fried Rupchanda', NULL, 79500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Fragrant Chicken Curry', NULL, 49500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Chicken Korma', NULL, 54500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Morog Polao', NULL, 52500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Shorshe Aloor Dom', NULL, 29500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Spicy Mixed Vegetable', NULL, 34500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Lamb Shank', NULL, 89500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Beef Paya', NULL, 52500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Spicy Beef Bhuna', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Duck Bhuna', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Mains'), 'Beef Kala Bhuna', NULL, 64500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Basmati Rice', NULL, 12500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Polao', NULL, 18500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Bhuna Khichuri', NULL, 17500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Naan', NULL, 7500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Porota', NULL, 7500),
  ((SELECT id FROM menu_categories WHERE name = 'Accompaniments'), 'Luchi (2 pieces)', NULL, 7500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Daal', NULL, 14500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Labra', NULL, 32500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Taki Bhorta', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Chingri Bhorta', NULL, 32500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Egg Curry', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Shared Dish'), 'Roasted Pigeon', NULL, 39500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Faluda', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Shahi Tukra', NULL, 12500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Coconut Ice Cream', NULL, 21500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Caramel Pudding', NULL, 17500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Doi Bora', NULL, 15500),
  ((SELECT id FROM menu_categories WHERE name = 'Desserts'), 'Paan Pistachio Ice Cream', NULL, 14500),
  ((SELECT id FROM menu_categories WHERE name = 'Kids Menu'), 'French Fries', NULL, 14500),
  ((SELECT id FROM menu_categories WHERE name = 'Kids Menu'), 'Chicken Nuggets', NULL, 29500),
  ((SELECT id FROM menu_categories WHERE name = 'Kids Menu'), 'Chicken Wings', NULL, 33000),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Lassi (Salted/Sweet)', NULL, 19500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Flavored Lassi', NULL, 21500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Lemonade', NULL, 17500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Mint Lemonade', NULL, 19500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Fresh Juice', NULL, 22500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Soft Drinks', NULL, 9500),
  ((SELECT id FROM menu_categories WHERE name = 'Drinks'), 'Masala Tea', NULL, 8000),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Espresso', NULL, 14000),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Americano', NULL, 16000),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Cappuccino', NULL, 19500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Hazelnut Cappuccino', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Caramel Cappuccino', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Latte', NULL, 19500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Hazelnut Latte', NULL, 25500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Caramel Latte', NULL, 25500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Mocha', NULL, 25500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Mocha Latte', NULL, 25500),
  ((SELECT id FROM menu_categories WHERE name = 'Coffee'), 'Hot Chocolate', NULL, 22500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Affogato', NULL, 22500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Oreo Frappe', NULL, 28500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Caramel Frappe', NULL, 28500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Matcha Latte', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Chocolate Milkshake', NULL, 18500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Vanilla Milkshake', NULL, 18500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Oreo Milkshake', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Red Velvet Milkshake', NULL, 24500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Flavoured Tea', NULL, 14500),
  ((SELECT id FROM menu_categories WHERE name = 'Featured'), 'Additional Whipped Cream', NULL, 3500);